### ISSUE TITLE
Any chance for an Android version in the future?

### ISSUE THREAD

**Issue by hamishmb** [4ch1m/huElectron#10]
This is really cool, I've been looking for a proper open-source/free software way to do this. As this is an Electron app, is there any chance there might be an Android port sometime? :)

**Comment by 4ch1m** [comment]
Nope.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/4ch1m/huElectron/issues/10#issue-1206469144

@hamishmb, https://github.com/Domi04151309/HomeApp/blob/c40fdf269526bc93124fe2fe37a59e983b30d60a/README.md#home-app-for-android may be of use.

**Comment by hamishmb** [comment]
Thanks, that was interesting to look at. Unfortunately, it seems to require the Hue Bridge, which I don't have, but thanks all the same.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/4ch1m/huElectron/issues/10#issuecomment-2048234509

@hamishmb, likewise - I've not one. If you find a solution, please reference it here.
