### ISSUE TITLE
Does this require a bridge?

### ISSUE THREAD

**Issue by hamishmb** [4ch1m/huElectron#11]
Hi there,

I was wondering if it would be possible to control a single light with bluetooth or if a bridge is required? I can't seem to do anything without adding a bridge (which I don't have).

**Comment by 4ch1m** [comment]
__Philips__ hue works with Zigbee, not bluetooth.
A bridge is required.

This is neither an issue of my app, nor is it the right place to discuss/explain how __hue__ works in general.

Closing.

**Comment by hamishmb** [comment]
I can control a Philips Hue Bulb using my phone with Bluetooth, so I beg to differ. My phone definitely doesn't have Zigbee, and I need Bluetooth enabled for the app to work, so I am confident that at least some of these products can be controlled with Bluetooth.

**Comment by 4ch1m** [comment]
You're right.
hue devices manufactured after ~2019 also come with integrated bluetooth.
__huElectron__ only operates via bridge though.

**Comment by hamishmb** [comment]
Ah right, that makes more sense. I'll keep an eye out in case one day you support Bluetooth :)
