### ISSUE TITLE
Provide a Flatpak package.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [4ch1m/huElectron#15]
My rationale is available at https://github.com/safing/portmaster-packaging/issues/43#issue-956312378#:~:text=It%20shall%20allow,to%20support%20this. I am thankful for any assistance.

**Comment by 4ch1m** [comment]
Please provide a pull-request containing all the necessary adjustments.
If the implementation has a "small footprint" (and is easy to maintain) then I'll consider to add it permanently.
Thank you.
